version: '3'
services:
  web:
    build: .
    ports:
    - "8000:8000"
    volumes:
    - .:/code
    entrypoint: /bin/sh
    command: -c "python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
